/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.testing.Presentacion;


/**
 *
 * @author pipo
 */
public class Presentacion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Presentacion.class.getName());

    public Presentacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane = new javax.swing.JDesktopPane();
        mbMain = new javax.swing.JMenuBar();
        mEmpresas = new javax.swing.JMenu();
        miCrearEmpresa = new javax.swing.JMenuItem();
        miListarEmpresas = new javax.swing.JMenuItem();
        mUsuarios = new javax.swing.JMenu();
        miUsuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SuperGestor");
        setMinimumSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new java.awt.BorderLayout(700, 800));

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        getContentPane().add(DesktopPane, java.awt.BorderLayout.CENTER);

        mEmpresas.setText("Empresas");

        miCrearEmpresa.setText("Crear empresa");
        miCrearEmpresa.addActionListener(this::miCrearEmpresaActionPerformed);
        mEmpresas.add(miCrearEmpresa);

        miListarEmpresas.setText("Listar empresas");
        miListarEmpresas.addActionListener(this::miListarEmpresasActionPerformed);
        mEmpresas.add(miListarEmpresas);

        mbMain.add(mEmpresas);

        mUsuarios.setText("Usuarios");

        miUsuarios.setText("Usuarios");
        miUsuarios.addActionListener(this::miUsuariosActionPerformed);
        mUsuarios.add(miUsuarios);

        mbMain.add(mUsuarios);

        setJMenuBar(mbMain);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCrearEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCrearEmpresaActionPerformed
        javax.swing.JInternalFrame internalFrame = new javax.swing.JInternalFrame("Crear Empresa",true,true,true,true);
        internalFrame.getContentPane().add(new CrearEmpresa());
        internalFrame.pack();
        this.DesktopPane.add(internalFrame);
        internalFrame.setVisible(true);
    }//GEN-LAST:event_miCrearEmpresaActionPerformed

    private void miListarEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListarEmpresasActionPerformed
        javax.swing.JInternalFrame internalFrame = new javax.swing.JInternalFrame("Empresas",true,true,true,true);
        internalFrame.getContentPane().add(new ListarEmpresas());
        internalFrame.pack();
        this.DesktopPane.add(internalFrame);
        internalFrame.setVisible(true);
    }//GEN-LAST:event_miListarEmpresasActionPerformed

    private void miUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUsuariosActionPerformed
        javax.swing.JInternalFrame internalFrame = new javax.swing.JInternalFrame("Usuarios",true,true,true,true);
        internalFrame.getContentPane().add(new Usuarios());
        internalFrame.pack();
        this.DesktopPane.add(internalFrame);
        internalFrame.setVisible(true);
    }//GEN-LAST:event_miUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Presentacion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenu mEmpresas;
    private javax.swing.JMenu mUsuarios;
    private javax.swing.JMenuBar mbMain;
    private javax.swing.JMenuItem miCrearEmpresa;
    private javax.swing.JMenuItem miListarEmpresas;
    private javax.swing.JMenuItem miUsuarios;
    // End of variables declaration//GEN-END:variables
}
