/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.testing.Presentacion;

import com.mycompany.testing.Logica.Fabrica;
import com.mycompany.testing.Logica.IControlador;
import com.mycompany.testing.Persistencia.DTempresa;
import com.mycompany.testing.Persistencia.DTusuario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pipo
 */
public class Usuarios extends javax.swing.JPanel {

    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
        cargarCbEmpresa();
        cargarTablaUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        cbEmpresa = new javax.swing.JComboBox<>();
        btnCrear = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnCumple = new javax.swing.JButton();

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Edad", "Empresa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Edad:");

        jLabel3.setText("Empresa:");

        btnCrear.setText("Crear");
        btnCrear.addActionListener(this::btnCrearActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnCumple.setText("Cumpleaños");
        btnCumple.addActionListener(this::btnCumpleActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnCrear)
                            .addGap(18, 18, 18)
                            .addComponent(btnEditar)
                            .addGap(18, 18, 18)
                            .addComponent(btnEliminar)
                            .addGap(18, 18, 18)
                            .addComponent(btnCumple)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(cbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnActualizar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnCumple))
                .addGap(18, 18, 18)
                .addComponent(btnActualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        try {
                String nombre = txtNombre.getText().trim();
                int edad = Integer.parseInt(txtEdad.getText().trim());
                String empresaSeleccionada = (String) cbEmpresa.getSelectedItem();

                if (nombre.isEmpty() || empresaSeleccionada == null) {
                    JOptionPane.showMessageDialog(this, "Debe completar el nombre y seleccionar una empresa.");
                    return;
                }

                IControlador ic = Fabrica.getInstance().getIControlador();
                ic.crearUsuario(nombre, edad, empresaSeleccionada);

                JOptionPane.showMessageDialog(this, "Usuario creado exitosamente.");
                cargarTablaUsuarios();
                txtNombre.setText("");
                txtEdad.setText("");

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "La edad debe ser un número entero.");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al crear usuario: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCumpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCumpleActionPerformed
        try {
                String nombre = txtNombre.getText().trim();
                if (nombre.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Seleccione un usuario de la tabla.");
                    return;
                }

                IControlador ic = Fabrica.getInstance().getIControlador();
                ic.celebrarCumpleanios(nombre);

                JOptionPane.showMessageDialog(this, "¡Feliz Cumpleaños! Edad actualizada.");
                cargarTablaUsuarios(); // Refresca la tabla mostrando la nueva edad

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al actualizar la edad: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCumpleActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        try {
                // 1. Obtener datos de los controles
                String nombre = txtNombre.getText().trim();
                String txtEdadVal = txtEdad.getText().trim();
                String empresaSeleccionada = (String) cbEmpresa.getSelectedItem();

                // 2. Validaciones básicas
                if (nombre.isEmpty() || txtEdadVal.isEmpty() || empresaSeleccionada == null) {
                    JOptionPane.showMessageDialog(this, 
                        "Debe seleccionar un usuario de la tabla y completar todos los datos.", 
                        "Advertencia", 
                        JOptionPane.WARNING_MESSAGE);
                    return;
                }

                int edad = Integer.parseInt(txtEdadVal);

                // 3. Invocar al controlador mediante la Fábrica
                IControlador ic = Fabrica.getInstance().getIControlador();
                ic.editarUsuario(nombre, edad, empresaSeleccionada);

                // 4. Notificar al usuario
                JOptionPane.showMessageDialog(this, 
                    "Usuario modificado correctamente.", 
                    "Éxito", 
                    JOptionPane.INFORMATION_MESSAGE);

                // 5. Refrescar la tabla y limpiar campos
                cargarTablaUsuarios();
                txtNombre.setText("");
                txtEdad.setText("");
                txtNombre.setEditable(true); // Liberar clave primaria si estaba bloqueada

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, 
                    "La edad debe ser un número entero válido.", 
                    "Error de formato", 
                    JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, 
                    "Error al editar usuario: " + e.getMessage(), 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Obtener el identificador
            String nombre = txtNombre.getText().trim();

            // 2. Validar que no esté vacío
            if (nombre.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "Debe seleccionar un usuario de la tabla para eliminar.", 
                    "Advertencia", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 3. Confirmación de seguridad
            int respuesta = JOptionPane.showConfirmDialog(
                this, 
                "¿Está seguro de que desea eliminar al usuario '" + nombre + "'?", 
                "Confirmar eliminación", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE
            );

            // Si el usuario hace clic en "Sí"
            if (respuesta == JOptionPane.YES_OPTION) {

                // 4. Invocar al controlador mediante la Fábrica
                IControlador ic = Fabrica.getInstance().getIControlador();
                ic.eliminarUsuario(nombre);

                // 5. Notificar
                JOptionPane.showMessageDialog(this, 
                    "Usuario eliminado correctamente.", 
                    "Éxito", 
                    JOptionPane.INFORMATION_MESSAGE);

                // 6. Refrescar la tabla y resetear controles
                cargarTablaUsuarios();
                txtNombre.setText("");
                txtEdad.setText("");
                txtNombre.setEditable(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error al eliminar usuario: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
    int fila = tbl.getSelectedRow();
        if (fila != -1) {
            String nombre = tbl.getValueAt(fila, 0).toString();
            String edad = tbl.getValueAt(fila, 1).toString();
            String empresa = tbl.getValueAt(fila, 2).toString();

            txtNombre.setText(nombre);
            txtEdad.setText(edad);
            cbEmpresa.setSelectedItem(empresa); // Selecciona la empresa en el combo
            txtNombre.setEditable(false); // Bloquea la PK al editar
        }
    }//GEN-LAST:event_tblMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        cargarCbEmpresa();
        cargarTablaUsuarios();
        txtNombre.setText("");
        txtEdad.setText("");
    }//GEN-LAST:event_btnActualizarActionPerformed

    
    
    
    
    private void cargarCbEmpresa(){
        try {
                cbEmpresa.removeAllItems();
                IControlador ic = Fabrica.getInstance().getIControlador();
                List<DTempresa> empresas = ic.listarEmpresas();

                for (DTempresa e : empresas) {
                    cbEmpresa.addItem(e.getNombre()); // Agregamos los nombres al combo
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al cargar empresas: " + e.getMessage());
        }
    }
    
    private void cargarTablaUsuarios(){
        try {
                IControlador ic = Fabrica.getInstance().getIControlador();
                List<DTusuario> usuarios = ic.listarUsuarios();

                DefaultTableModel model = (DefaultTableModel) tbl.getModel();
                model.setRowCount(0);

                for (DTusuario u : usuarios) {
                    model.addRow(new Object[]{ u.getNombre(), u.getEdad(), u.getEmpresa() });
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al cargar usuarios: " + e.getMessage());
            }        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnCumple;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cbEmpresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
