/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.testing.Presentacion;
import com.mycompany.testing.Logica.Fabrica;
import com.mycompany.testing.Logica.IControlador;
import com.mycompany.testing.Persistencia.DTempresa;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pipo
 */
public class ListarEmpresas extends javax.swing.JPanel {

    /**
     * Creates new form ListarEmpresas
     */
    public ListarEmpresas() {
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnActualizar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblCreacion = new javax.swing.JLabel();
        txtCreacion = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(this::btnBorrarActionPerformed);

        lblNombre.setText("Nombre:");

        lblCreacion.setText("Creacion:");

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Creacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnActualizar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditar)
                                .addGap(18, 18, 18)
                                .addComponent(btnBorrar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCreacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreacion)
                    .addComponent(txtCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnEditar)
                    .addComponent(btnBorrar))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        try {
            // 1. Obtener el nombre de los campos de texto
            String nombre = txtNombre.getText().trim();

            // 2. Validar que haya un nombre seleccionado/ingresado
            if (nombre.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "Debe seleccionar una empresa de la tabla para eliminar.", 
                    "Advertencia", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 3. Confirmación de seguridad
            int respuesta = JOptionPane.showConfirmDialog(
                this, 
                "¿Está seguro de que desea eliminar la empresa '" + nombre + "'?", 
                "Confirmar eliminación", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE
            );

            // Si el usuario hace clic en "Sí" (YES_OPTION)
            if (respuesta == JOptionPane.YES_OPTION) {

                // 4. Invocar al controlador mediante la Fábrica
                IControlador ic = Fabrica.getInstance().getIControlador();
                ic.eliminarEmpresa(nombre);

                // 5. Notificar al usuario
                JOptionPane.showMessageDialog(this, 
                    "Empresa eliminada correctamente.", 
                    "Éxito", 
                    JOptionPane.INFORMATION_MESSAGE);

                // 6. Refrescar la tabla y resetear los campos
                cargarTabla();
                txtNombre.setText("");
                txtCreacion.setText("");
            }

        } catch (Exception e) {JOptionPane.showMessageDialog(this,"Error al eliminar la empresa: " + e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Obtener los datos de los campos de texto
            String nombre = txtNombre.getText().trim();
            String creacion = txtCreacion.getText().trim();

            // 2. Validar que no estén vacíos
            if (nombre.isEmpty() || creacion.isEmpty()) {
                JOptionPane.showMessageDialog(this,"Debe seleccionar una empresa de la tabla y completar los datos.","Advertencia",JOptionPane.WARNING_MESSAGE);
                return;
            }

            int anioCreacion = Integer.parseInt(creacion);

            // 3. Invocar al controlador mediante la Fábrica
            IControlador ic = Fabrica.getInstance().getIControlador();
            ic.editarEmpresa(nombre, anioCreacion);

            // 4. Notificar al usuario
            JOptionPane.showMessageDialog(this,"Empresa modificada correctamente.","Éxito",JOptionPane.INFORMATION_MESSAGE);

            // 5. Refrescar la tabla y limpiar campos
            cargarTabla();
            txtNombre.setText("");
            txtCreacion.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"El año de creación debe ser un número entero válido.","Error de formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {JOptionPane.showMessageDialog(this,"Error al editar: " + e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        cargarTabla();
        
        txtNombre.setText("");
        txtCreacion.setText("");
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = tbl.getSelectedRow();
        
        if (filaSeleccionada != -1){
            String nombre = tbl.getValueAt(filaSeleccionada,0).toString();
            String creacion = tbl.getValueAt(filaSeleccionada,1).toString();

            txtNombre.setText(nombre);
            txtCreacion.setText(creacion);
        }
    }//GEN-LAST:event_tblMouseClicked

    private void cargarTabla(){
        try {
            // 1. Obtener la interfaz del controlador a través de la fábrica
            IControlador ic = Fabrica.getInstance().getIControlador();

            // 2. Traer la lista de DataTypes
            List<DTempresa> lista = ic.listarEmpresas();

            // 3. Obtener el modelo de la tabla existente
            DefaultTableModel model = (DefaultTableModel) tbl.getModel();

            // 4. Limpiar las filas previas
            model.setRowCount(0);

            // 5. Cargar los nuevos datos
            for (DTempresa e : lista) {
                model.addRow(new Object[]{ e.getNombre(), e.getCreacion() });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error al actualizar la tabla: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreacion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtCreacion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
